import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";


import NavigationBar from '../components/navbar';
import 'bootstrap/dist/css/bootstrap.css'
import { Nav, Navbar, NavDropdown } from 'react-bootstrap'

export default function Home() {
  


  return (
      <>
      <NavigationBar/>
      
      <Head>
        <title>BackseatDrivers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      <p className = {styles.spacing}>
        
      </p>

      <main className={styles.main}>
        
        <h1 className={styles.title}>
          Welcome to Backseat Drivers!  
        </h1>

        <p className={styles.description}>
          <Image src="/favicon.jpg" alt="favicon  .jpg" width={150} height={150}></Image>
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <a href="/drivers" className={styles.card}>
            <h2>Post a Ride</h2>
            <p>Click here to post a ride!</p>
          </a>
          
          <a
            href="/postings"
            className={styles.card}
          >
            <h2>Find a Ride</h2>
            <p>Click here to view a ride!</p>
          </a>
        </div>
      </main>

    </>
  )
}
